version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/offen
    steps:
      - checkout
      - install_packer:
          version: '1.5.6'
      - run:
          name: Build image on remote droplet
          command: packer build marketplace-image.json

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DigitalOcean
          filters:
            branches:
              only:
                - master

commands:
  install_packer:
    parameters:
      version:
        description: The packer version to install
        type: string
    steps:
      - run:
          name: Install packer
          command: |
            wget https://releases.hashicorp.com/packer/<< parameters.version >>/packer_<< parameters.version >>_linux_amd64.zip -O /tmp/packer.zip
            mkdir -p /tmp/packer-bin
            unzip /tmp/packer.zip -d /tmp/packer-bin
            sudo ln -s /tmp/packer-bin/packer /usr/local/bin/packer
            which packer
