#!/bin/bash
set -eo pipefail

mkdir -p /tmp/offen-download && cd /tmp/offen-download
curl -L https://get.offen.dev/$OFFEN_VERSION | tar -xvz
mkdir -p /opt/offen/$OFFEN_VERSION
cp offen-linux-amd64 /opt/offen/$OFFEN_VERSION
ln -s /opt/offen/$OFFEN_VERSION/offen-linux-amd64 /usr/bin/offen

mkdir -p /var/opt/offen
mkdir -p /var/www/.cache
mkdir -p /etc/offen && touch /etc/offen/offen.env
