#!/bin/bash
set -eo pipefail

configure_service () {
  touch /etc/systemd/system/offen.service
  cat > /etc/systemd/system/offen.service <<EOF
[Unit]
Description=Offen Service

[Service]
ExecStart=/usr/bin/offen
Restart=always

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable offen
}

echo "---> Configuring systemd service..."
configure_service
echo "---> Successfully set up service."
