#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Thank you for using Offen! If you have just deployed the application head
to "/setup" in your browser to finish the installation process.

Find our documentation at: https://docs.offen.dev

If you need support, send us an email at hioffen@posteo.de, tweet @hioffen
or open an issue on our GitHub repository: https://github.com/offen/offen

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
